services:
    ndb:
        container_name: national-database
        image: postgres
        restart: unless-stopped
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"

    phoenix:
        container_name: phoenix-app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ndb:5432/${POSTGRES_DB}
            - SECRET_KEY_BASE=${SECRET_KEY_BASE}
            - PHX_HOST=${PHX_HOST}
            - PORT=4000
        ports:
            - "${PHX_PORT}:${PHX_PORT}"
        depends_on:
            - ndb

volumes:
    postgres-data: {}
