services:
    ndb:
        container_name: national-database
        image: postgres
        restart: unless-stopped
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        # command: ["postgres", "-N", "5000"]
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

volumes:
    postgres-data: {}
