apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-api-deployment
  labels:
    app: ndb-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ndb-rest-api
  template:
    metadata:
      labels:
        app: ndb-rest-api
    spec:
      containers:
      - name: ndb-rest-api
        image: visco01/ndb-rest-api:main
        ports:
        - containerPort: 4000
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PORT
        - name: DATABASE_URL
          value: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ndb-service:5432/${POSTGRES_DB}"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: SECRET_KEY_BASE
---
apiVersion: v1
kind: Service
metadata:
  name: ndb-rest-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30002
  selector:
    app: ndb-rest-api
